import{createClient}from"https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
const sb=createClient("https://bbwbaohkbxsjumkfknqn.supabase.co","sb_publishable_5mdYxS9nGFb3DoxbdsdiAg_dOCOnTP5"),WA="5493743512413",$=s=>document.querySelector(s);
let subs=[],prods=[],vars=[],filter=null,cart=[];
const money=n=>new Intl.NumberFormat("es-AR",{style:"currency",currency:"ARS",maximumFractionDigits:0}).format(Number(n)||0),esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c])),qty=()=>cart.reduce((a,x)=>a+x.n,0),isWholesale=()=>qty()>=10,unitPrice=p=>Number(isWholesale()?(p.wholesale_price??p.price):p.price)||0;
$("#wa").href="https://wa.me/"+WA+"?text="+encodeURIComponent("Hola CUBIC, quería hacer una consulta.");
function norm(v){v=(v||"").trim();if(!v)return"https://instagram.com/";if(v.startsWith("http"))return v;if(v.startsWith("@"))v=v.slice(1);return"https://instagram.com/"+v.replace(/^\/+|\/+$/g,"")}
function setLogo(url){const img=$("#siteLogo"),fb=$("#logoFallback");if(url){img.src=url;img.hidden=false;fb.hidden=true;img.onerror=()=>{img.hidden=true;fb.hidden=false}}else{img.hidden=true;fb.hidden=false}}
function openZoom(src){if(!src)return;$("#zoomImg").src=src;$("#lightbox").classList.add("open")}function closeZoom(){$("#lightbox").classList.remove("open");$("#zoomImg").src=""}
async function load(){const[a,b,c,d]=await Promise.all([sb.from("subcategories").select("*").eq("active",true).order("sort_order"),sb.from("products").select("*").eq("active",true).order("sort_order"),sb.from("product_variants").select("*").eq("active",true).order("sort_order"),sb.from("site_settings").select("*")]);subs=a.data||[];prods=b.data||[];vars=c.data||[];const s=d.data||[];$("#ig").href=norm(s.find(x=>x.key==="instagram_url")?.value);setLogo(s.find(x=>x.key==="logo_url")?.value||"");brands();render();cartRender()}
function brands(){const box=$("#brands");box.innerHTML="";subs.forEach(s=>{const b=document.createElement("button");b.className="nav"+(filter===s.id?" on":"");b.innerHTML="<span>"+esc(s.name)+"</span><span>›</span>";b.onclick=()=>{filter=s.id;brands();render();if(innerWidth<=900)$("#catAside").classList.remove("open")};box.appendChild(b)});const a=document.querySelector("[data-all]");a.className="nav"+(!filter?" on":"");a.onclick=()=>{filter=null;brands();render();if(innerWidth<=900)$("#catAside").classList.remove("open")}}
function render(){const q=$("#q").value.toLowerCase().trim(),list=prods.filter(p=>(!filter||p.subcategory_id===filter)&&(!q||[p.name,p.description,subs.find(s=>s.id===p.subcategory_id)?.name].join(" ").toLowerCase().includes(q))),box=$("#products");box.innerHTML="";if(!list.length){box.innerHTML='<div class="empty">Todavía no hay productos cargados.</div>';return}for(const p of list){const pv=vars.filter(v=>v.product_id===p.id),first=pv[0],wh=p.wholesale_price??p.price,el=document.createElement("article");el.className="card";el.dataset.v=first?.id||"";el.innerHTML='<div class="pic"><img loading="lazy" src="'+esc(first?.image_url||p.main_image_url||"")+'" alt="'+esc(p.name)+'"><span class="zoomHint">Tocá para ampliar</span></div><div class="body"><h3>'+esc(p.name)+'</h3><div class="muted">'+esc(subs.find(s=>s.id===p.subcategory_id)?.name||"")+'</div>'+(pv.length?'<div class="variants">'+pv.map((v,i)=>'<button class="variant '+(i?"":"on")+'" data-id="'+v.id+'" data-img="'+esc(v.image_url||p.main_image_url||"")+'">'+esc(v.name)+'</button>').join("")+'</div>':"")+'<div class="priceBlock"><div class="retail">Minorista: '+money(p.price)+'</div><div class="wholesale">Mayorista: '+money(wh)+'</div><div class="smallNote">Precio mayorista desde 10 unidades totales en el carrito.</div></div><button class="btn violet add">Agregar al carrito</button></div>';const img=el.querySelector(".pic img");el.querySelector(".pic").onclick=()=>openZoom(img.src);el.querySelectorAll(".variant").forEach(b=>b.onclick=e=>{e.stopPropagation();el.querySelectorAll(".variant").forEach(x=>x.classList.remove("on"));b.classList.add("on");el.dataset.v=b.dataset.id;img.src=b.dataset.img});el.querySelector(".add").onclick=()=>add(p.id,el.dataset.v);box.appendChild(el)}}
function add(pid,vid){const k=pid+"::"+vid,x=cart.find(i=>i.k===k);x?x.n++:cart.push({k,pid,vid,n:1});cartRender()}
function cartRender(){const q=qty(),wh=isWholesale();$("#cc").textContent=q;const st=$("#cartStatus");st.className="cartStatus "+(wh?"wholesaleMode":"retailMode");st.innerHTML=wh?'<b>Precio mayorista activado</b><br><span class="muted">Tenés '+q+' unidades en el carrito.</span>':'<b>Precio minorista</b><br><span class="muted">Agregá '+(10-q)+' unidad'+(10-q===1?"":"es")+' más para acceder al precio mayorista.</span>';const box=$("#items");box.innerHTML=cart.length?"":"<p class='muted'>Todavía no agregaste productos.</p>";for(const i of cart){const p=prods.find(x=>x.id===i.pid),v=vars.find(x=>x.id===i.vid),u=unitPrice(p),d=document.createElement("div");d.className="cartItem";d.innerHTML='<img src="'+esc(v?.image_url||p?.main_image_url||"")+'"><div><b>'+esc(p?.name)+'</b><div class="muted">'+esc(v?.name||"")+'</div><div class="smallNote">'+(wh?"Mayorista":"Minorista")+': '+money(u)+' c/u</div><div class="qty"><button data-d="-1">−</button><span>'+i.n+'</span><button data-d="1">+</button></div></div><b>'+money(u*i.n)+'</b>';d.querySelectorAll("[data-d]").forEach(b=>b.onclick=()=>{i.n+=Number(b.dataset.d);if(i.n<=0)cart=cart.filter(x=>x.k!==i.k);cartRender()});box.appendChild(d)}const t=cart.reduce((a,i)=>a+unitPrice(prods.find(p=>p.id===i.pid))*i.n,0);$("#total").textContent=money(t);const lines=["Hola CUBIC, quiero realizar este pedido:","",wh?"PRECIO MAYORISTA APLICADO (10+ unidades)":"PRECIO MINORISTA",""];for(const i of cart){const p=prods.find(x=>x.id===i.pid),v=vars.find(x=>x.id===i.vid),u=unitPrice(p);lines.push(i.n+" × "+p.name+" — "+money(u)+" c/u");if(v)lines.push("Variante: "+v.name);lines.push("Subtotal: "+money(u*i.n),"")}lines.push("Cantidad total: "+q+" unidades","TOTAL: "+money(t));$("#send").href=cart.length?"https://wa.me/"+WA+"?text="+encodeURIComponent(lines.join("\n")):"#";$("#send").style.pointerEvents=cart.length?"auto":"none";$("#send").style.opacity=cart.length?"1":".5"}
$("#q").oninput=render;$("#cartBtn").onclick=()=>$("#shade").classList.add("open");$("#close").onclick=()=>$("#shade").classList.remove("open");$("#shade").onclick=e=>{if(e.target===$("#shade"))$("#shade").classList.remove("open")};$("#catToggle").onclick=()=>$("#catAside").classList.toggle("open");$("#zoomClose").onclick=closeZoom;$("#lightbox").onclick=e=>{if(e.target===$("#lightbox"))closeZoom()};document.addEventListener("keydown",e=>{if(e.key==="Escape")closeZoom()});load();