import{createClient}from"https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
const sb=createClient("https://bbwbaohkbxsjumkfknqn.supabase.co","sb_publishable_5mdYxS9nGFb3DoxbdsdiAg_dOCOnTP5"),$=s=>document.querySelector(s);
let user,cats=[],subs=[],prods=[],draft=[];
const money=n=>new Intl.NumberFormat("es-AR",{style:"currency",currency:"ARS",maximumFractionDigits:0}).format(Number(n)||0);
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
async function canvasBlob(c,q){return new Promise((r,j)=>c.toBlob(b=>b?r(b):j(new Error("No se pudo optimizar la imagen.")),"image/webp",q))}
async function optimizeImage(f,max=1800,q=.84){if(!f)return null;const b=await createImageBitmap(f),s=Math.min(1,max/Math.max(b.width,b.height)),w=Math.max(1,Math.round(b.width*s)),h=Math.max(1,Math.round(b.height*s)),c=document.createElement("canvas");c.width=w;c.height=h;c.getContext("2d",{alpha:true}).drawImage(b,0,0,w,h);let x=await canvasBlob(c,q);b.close?.();return new File([x],f.name.replace(/\.[^.]+$/,"")+".webp",{type:"image/webp"})}
async function upload(f,prefix=""){if(!f)return null;const o=await optimizeImage(f,prefix==="logo-"?700:1800,prefix==="logo-"?.9:.84),p=user.id+"/"+prefix+crypto.randomUUID()+".webp",r=await sb.storage.from("product-images").upload(p,o,{cacheControl:"31536000",contentType:"image/webp"});if(r.error)throw r.error;return sb.storage.from("product-images").getPublicUrl(p).data.publicUrl}
async function start(){const s=(await sb.auth.getSession()).data.session;user=s?.user;if(!user)return;const a=await sb.from("admin_users").select("user_id").eq("user_id",user.id).maybeSingle();if(!a.data){$("#loginBox").classList.add("hidden");$("#pending").classList.remove("hidden");return}$("#loginBox").classList.add("hidden");$("#adm").classList.remove("hidden");await load()}
$("#login").onsubmit=async e=>{e.preventDefault();const r=await sb.auth.signInWithPassword({email:$("#email").value,password:$("#pass").value});$("#msg").textContent=r.error?r.error.message:"";$("#msg").className=r.error?"danger":"";if(!r.error)start()};
$("#logout").onclick=async()=>{await sb.auth.signOut();location.reload()};
async function load(){const[a,b,c,d]=await Promise.all([sb.from("categories").select("*"),sb.from("subcategories").select("*").order("sort_order"),sb.from("products").select("*").order("created_at",{ascending:false}),sb.from("site_settings").select("*")]);cats=a.data||[];subs=b.data||[];prods=c.data||[];const s=d.data||[];$("#igInput").value=s.find(x=>x.key==="instagram_url")?.value||"";const logo=s.find(x=>x.key==="logo_url")?.value||"";$("#logoPreview").src=logo||"data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http://www.w3.org/2000/svg' width='300' height='200'%3E%3Crect width='100%25' height='100%25' fill='%23111116'/%3E%3Ctext x='50%25' y='50%25' fill='white' font-size='28' text-anchor='middle' dominant-baseline='middle'%3ECUBIC%3C/text%3E%3C/svg%3E";$("#ps").innerHTML=subs.map(s=>'<option value="'+s.id+'">'+esc(s.name)+'</option>').join("");$("#brandList").innerHTML=subs.map(s=>'<span class="chip">'+esc(s.name)+'</span>').join("");renderProducts()}
$("#logoFile").onchange=e=>{const f=e.target.files[0];if(f)$("#logoPreview").src=URL.createObjectURL(f)};
$("#logoForm").onsubmit=async e=>{e.preventDefault();const b=e.submitter,old=b.textContent;try{b.disabled=true;b.textContent="Comprimiendo y guardando...";const f=$("#logoFile").files[0],url=await upload(f,"logo-");const r=await sb.from("site_settings").upsert({key:"logo_url",value:url,updated_at:new Date().toISOString()});if(r.error)throw r.error;$("#logoPreview").src=url;$("#logoMsg").textContent="Logo actualizado. La tienda lo toma automáticamente.";$("#logoFile").value=""}catch(err){alert(err.message||err)}finally{b.disabled=false;b.textContent=old}};
$("#igForm").onsubmit=async e=>{e.preventDefault();const r=await sb.from("site_settings").upsert({key:"instagram_url",value:$("#igInput").value.trim(),updated_at:new Date().toISOString()});alert(r.error?r.error.message:"Instagram guardado.")};
function mainCat(){return cats.find(c=>c.slug==="graficas-de-motos")||cats[0]}
$("#brandForm").onsubmit=async e=>{e.preventDefault();const n=$("#brandName").value.trim(),slug=n.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");if(!n)return;const r=await sb.from("subcategories").insert({category_id:mainCat().id,name:n,slug,sort_order:subs.length+1,active:true});if(r.error)return alert(r.error.message);$("#brandName").value="";load()};
function variantRows(){const b=$("#vrows");b.innerHTML="";draft.forEach((v,i)=>{const r=document.createElement("div");r.className="vr";r.innerHTML='<input class="vn" placeholder="Ej.: Roja" value="'+esc(v.name||"")+'"><input class="vf" type="file" accept="image/*"><button type="button" class="btn">Quitar</button>';r.querySelector(".vn").oninput=e=>v.name=e.target.value;r.querySelector(".vf").onchange=e=>v.file=e.target.files[0];r.querySelector("button").onclick=()=>{draft.splice(i,1);variantRows()};b.appendChild(r)})}
$("#addV").onclick=()=>{draft.push({name:"",file:null});variantRows()};
function clearForm(){$("#pf").reset();$("#pid").value="";$("#ft").textContent="Agregar producto";$("#pa").checked=true;draft=[];variantRows()}
$("#clear").onclick=clearForm;
function editProduct(p){$("#pid").value=p.id;$("#ft").textContent="Editar producto";$("#pn").value=p.name;$("#pp").value=p.price;$("#pw").value=p.wholesale_price??p.price;$("#ps").value=p.subcategory_id;$("#pd").value=p.description||"";$("#pa").checked=p.active;draft=[];variantRows();scrollTo({top:0,behavior:"smooth"})}
function renderProducts(){const b=$("#plist");b.innerHTML=prods.length?"":"<p class='muted'>Todavía no cargaste productos.</p>";prods.forEach(p=>{const r=document.createElement("div");r.className="prodRow";r.innerHTML='<img src="'+esc(p.main_image_url||"")+'"><div><b>'+esc(p.name)+'</b><div class="muted">'+esc(subs.find(s=>s.id===p.subcategory_id)?.name||"")+'</div><div>Minorista: '+money(p.price)+' · Mayorista: '+money(p.wholesale_price??p.price)+'</div></div><div><button class="btn ed">Editar</button> <button class="btn del">Eliminar</button></div>';r.querySelector(".ed").onclick=()=>editProduct(p);r.querySelector(".del").onclick=async()=>{if(confirm("¿Eliminar producto?")){await sb.from("products").delete().eq("id",p.id);load()}};b.appendChild(r)})}
$("#pf").onsubmit=async e=>{e.preventDefault();const s=e.submitter,o=s?.textContent;try{if(s){s.disabled=true;s.textContent="Optimizando y guardando..."}const id=$("#pid").value,img=await upload($("#pi").files[0]),data={category_id:mainCat().id,subcategory_id:$("#ps").value,name:$("#pn").value.trim(),price:Number($("#pp").value),wholesale_price:Number($("#pw").value),description:$("#pd").value.trim(),active:$("#pa").checked};if(img)data.main_image_url=img;let pid=id;if(id){const r=await sb.from("products").update(data).eq("id",id);if(r.error)throw r.error}else{const r=await sb.from("products").insert(data).select("id").single();if(r.error)throw r.error;pid=r.data.id}for(let i=0;i<draft.length;i++){const v=draft[i];if(!v.name.trim()||!v.file)continue;const im=await upload(v.file),r=await sb.from("product_variants").insert({product_id:pid,name:v.name.trim(),image_url:im,sort_order:i+1,active:true});if(r.error)throw r.error}clearForm();await load();alert("Producto guardado.")}catch(err){alert(err.message||err)}finally{if(s){s.disabled=false;s.textContent=o||"Guardar producto"}}};
start();